// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqp3IHOlhaKdYq2aOGwX8uB7P1ghnZ-sM',
    appId: '1:999082995167:web:4747ffdaedd87ac15a286a',
    messagingSenderId: '999082995167',
    projectId: 'app-bloc-auth',
    authDomain: 'app-bloc-auth.firebaseapp.com',
    storageBucket: 'app-bloc-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnh7iivMcjdWtZNgWIDf6ttx_zOtPCFGM',
    appId: '1:999082995167:android:3e32cf5d27c551055a286a',
    messagingSenderId: '999082995167',
    projectId: 'app-bloc-auth',
    storageBucket: 'app-bloc-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiZ9qNRpssp4zOiasbTAYeRZxz9vxsB5o',
    appId: '1:999082995167:ios:f50c9f55da0df6e25a286a',
    messagingSenderId: '999082995167',
    projectId: 'app-bloc-auth',
    storageBucket: 'app-bloc-auth.appspot.com',
    iosClientId: '999082995167-nbvteij4evqr37a4hmb8nibu6llvq7v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.appBlocAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiZ9qNRpssp4zOiasbTAYeRZxz9vxsB5o',
    appId: '1:999082995167:ios:f50c9f55da0df6e25a286a',
    messagingSenderId: '999082995167',
    projectId: 'app-bloc-auth',
    storageBucket: 'app-bloc-auth.appspot.com',
    iosClientId: '999082995167-nbvteij4evqr37a4hmb8nibu6llvq7v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.appBlocAuth',
  );
}
